from .config import FISH_GAME_REGION, FISH_ENDURANCE_REGION
from .config import YELLOW_LOW, YELLOW_HIGH
from .config import PROJECT_PATH
from .config import DIST_PATH, WORK_PATH, SPEC_PATH, REC_MODEL_PATH, DET_MODEL_PATH
from .config import WHITE_BLOCK_AREA_MIN, WHITE_BLOCK_AREA_MAX, WHITE_BLOCK_SOLIDITY

__all__ = ["FISH_GAME_REGION", "FISH_ENDURANCE_REGION", "YELLOW_LOW",
           "YELLOW_HIGH", "PROJECT_PATH", "DIST_PATH", "WORK_PATH", "SPEC_PATH",
           "REC_MODEL_PATH", "DET_MODEL_PATH", "WHITE_BLOCK_AREA_MIN", "WHITE_BLOCK_AREA_MAX",
           "WHITE_BLOCK_SOLIDITY"]
